### ISSUE TITLE
Firefox background-visibility

### ISSUE THREAD

**Issue by jwo** [samkap/command-line-starter-kit#4]
So in Firefox 37.02 (current), the backface visibility doesn't seem to work once clicked.

I tried to figure this out, but it was basically ETOOMANYSTUPIDS. maybe ETOOMANYTACOS.

Works fine in chrome. love this site.

![screen shot 2015-05-05 at 4 39 34 pm](https://cloud.githubusercontent.com/assets/123075/7483539/6189f884-f345-11e4-9367-7d1315dbe7a8.png)

**Comment by samkap** [comment]
Thanks @jwo and @atmartin for the fix!
